# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: pg_database
    image: postgres
    restart: always
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    hostname: '${DATABASE_HOST}'
    environment:
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
