// This file was generated by Prisma and assumes you have installed the following:
// pnpm add -D prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

// Get database URL with fallback - use process.env directly to avoid failing when vars are not set
function getDatabaseUrl(): string {
  return (
    process.env.POSTGRES_URL ||
    process.env.PRISMA_DATABASE_URL ||
    process.env.DATABASE_URL ||
    'postgresql://postgres:postgres@localhost:5432/ecommerce?schema=public'
  );
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    // Priority: POSTGRES_URL (Vercel) > PRISMA_DATABASE_URL (Accelerate/direct) > DATABASE_URL (local)
    url: getDatabaseUrl(),
  },
});
