export const LIST_PRODUCTS_REQUESTED = "auth/LIST_PRODUCTS_REQUESTED";
export const LIST_PRODUCTS_FULFILLED = "auth/LIST_PRODUCTS_FULFILLED";
export const LIST_PRODUCTS_REJECTED = "auth/LIST_PRODUCTS_REJECTED";