export const LIST_PRODUCTS_REQUESTED = "products/LIST_PRODUCTS_REQUESTED";
export const LIST_PRODUCTS_FULFILLED = "products/LIST_PRODUCTS_FULFILLED";
export const LIST_PRODUCTS_REJECTED = "products/LIST_PRODUCTS_REJECTED";

export const DETAIL_PRODUCT_REQUESTED = "products/DETAIL_PRODUCT_REQUESTED";
export const DETAIL_PRODUCT_FULFILLED = "products/DETAIL_PRODUCT_FULFILLED";
export const DETAIL_PRODUCT_REJECTED = "products/DETAIL_PRODUCT_REJECTED";

export const ATT_PRODUCTS = "products/ATT_PRODUCTS";
